betterfuture/footprints/urls.py
from django.urls import path

from .views import (
    item_list_view,
    item_detail_view,
    organization_list_view,
    organization_detail_view,
    pedometer_create_view,
    pet_create_view,
    donate_create_view
)

app_name = "footprints"

urlpatterns = [
    path("shop/", view=item_list_view, name="item_list"),
    path("shop/<str:pk>", view=item_detail_view, name="item_detail"),

    path("donate/", view=organization_list_view, name="org_list"),
    path("donate/<str:pk>", view=organization_detail_view, name="org_detail"),
    path("donate/create/<str:org_pk>", view=donate_create_view, name="org_create"),

    path("pedometer/", view=pedometer_create_view, name="pedometer_create"),
    path("pet/", view=pet_create_view, name="pet_create"),
]

betterfuture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('betterfuture.users.urls', namespace='users')),
    path('footprints/', include('betterfuture.footprints.urls', namespace='footprints')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

betterfuture/users/urls.py
from django.urls import path

from .views import (
    user_dashboard_view,
    user_diagnostic_view
)

app_name = "users"
urlpatterns = [
    path("", view=user_dashboard_view, name="dashboard"),
    path("diagnostic/", view=user_diagnostic_view, name="diagnostic"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
<ul>
    {% if user.is_authenticated %}
    <li>Hello {{ user }}</li>
    <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
    <li><a href="{% url 'footprints:item_list' %}">Shop</a></li>
    <li><a href="{% url 'footprints:org_list' %}">Donate</a></li>
    <li><a href="{% url 'footprints:pedometer_create' %}">Pedometer</a></li>
    <li><a href="{% url 'footprints:pet_create' %}">Recycle</a></li>
    <li><a href="{% url 'account_logout' %}">Log out</a></li>
    <h3>
        You owe me <b>{{user.userco2.get_co2}} CO2</b>
    </h3>
    
    <h3>
        You have <b>{{ user.usertoken.tokens }} Tokens</b>
    </h3>
    {% else %}
    <li><a href="{% url 'account_login' %}">Log in</a></li>
    <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
    {% endif %}

</ul>

{% block content %}
defolt
{% endblock content %}
</body>

</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}
hello
{% endblock content %}